apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
  labels:
    type: local
spec:
  storageClassName: influxdb-volume
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data_influxdb"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      name: influxdb-port
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: influxdb-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
      containers:
      - name: influxdb
        image: my_influx
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
          - name: influxdb-volume
            mountPath: /root/.influxdb/
