apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-pasv
      protocol: TCP
      port: 21000
      targetPort: 21000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-cont
        image: my_ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 21000