apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: php-ma
spec:
  selector:
    app: php-ma
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - protocol: TCP
      port: 5000
      name: wp-port
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    app: php-ma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-ma
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-ma
        tier: frontend
    spec:
      containers:
      - name: php-ma
        image: my_php
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: php-ma
