apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
  - protocol: TCP
    port: 3000
    name: https
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
        app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: my_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
